# Generated by Django 2.2.5 on 2020-06-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_import', models.CharField(max_length=200)),
                ('type_import', models.CharField(max_length=3)),
                ('rarity_import', models.CharField(max_length=3)),
                ('set_import', models.CharField(max_length=75)),
                ('price_import', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_import', models.IntegerField()),
            ],
        ),
    ]
