# Generated by Django 2.2.5 on 2020-06-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgdatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='movement_price',
            field=models.FloatField(editable=False),
        ),
    ]
