# Generated by Django 2.2.5 on 2020-06-08 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgdatabase', '0002_auto_20200608_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decklist',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Quantity in Deck must be greater than 1')]),
        ),
    ]
