# Generated by Django 2.2.5 on 2020-06-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgdatabase', '0003_auto_20200608_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('CTR', 'Creature'), ('ART', 'Artifact'), ('EMT', 'Enchantment'), ('PLW', 'Planeswalker'), ('INT', 'Instant'), ('SOR', 'Sorcery'), ('LAN', 'Land')], default='CTR', max_length=3, verbose_name='Card Type'),
        ),
    ]
