# Generated by Django 2.2.5 on 2020-07-02 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtgdatabase', '0004_auto_20200621_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpansionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expansion_name', models.CharField(max_length=75)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='expansion_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtgdatabase.ExpansionSet'),
        ),
    ]
