# Generated by Django 2.2.5 on 2020-07-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgdatabase', '0005_auto_20200702_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expansionset',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
