# Generated by Django 2.2.5 on 2020-07-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgdatabase', '0007_card_collector_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='constructed',
            field=models.BooleanField(default=False),
        ),
    ]
