# Generated by Django 2.2.5 on 2020-11-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgdatabase', '0008_deck_constructed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=50, verbose_name='Forex Pair')),
                ('rate', models.DecimalField(decimal_places=7, max_digits=8, verbose_name='FX Rate')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='Last edited')),
            ],
        ),
    ]
