# Generated by Django 2.2.5 on 2021-03-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgdatabase', '0009_forex'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image_id',
            field=models.CharField(default='mtgdatabase\x07ssets\\card-front\\default.jpg', max_length=50, verbose_name='Image ID'),
        ),
    ]
